[PARAMETERS]
N_STATES = 3 # 0: EMPTY; 1: TREE; 2: BURNING
NT = 1000
W = 128
H = 128
SEED = 1089123

[INITIALISATION]
TYPE = "rects" # "random" "rects"
# A rect is [oi, oj, w, h] (1-index for i and j)
STATE_RECTS  = [
        [0, [  1,   1, 128, 128]],
        [1, [  2,   2, 126, 126]],
        [2, [ 63,  63,  2,    2]]
    ]
